### ISSUE TITLE
ModuleNotFoundError: No module named 'actual.utils'

### ISSUE THREAD

**Issue by wbradley93** [bvanelli/actualpy#36]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of actualpy.

### Reproducible example

```python
>>> from actual import Actual
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wes/.local/lib/python3.12/site-packages/actual/__init__.py", line 18, in <module>
    from actual.api import ActualServer
  File "/home/wes/.local/lib/python3.12/site-packages/actual/api/__init__.py", line 9, in <module>
    from actual.api.models import (
  File "/home/wes/.local/lib/python3.12/site-packages/actual/api/models.py", line 8, in <module>
    from actual.api.bank_sync import BankSyncAccountData, BankSyncTransactionData
  File "/home/wes/.local/lib/python3.12/site-packages/actual/api/bank_sync.py", line 10, in <module>
    from actual.utils.title import title
ModuleNotFoundError: No module named 'actual.utils'
```

### Issue description

Unable to import main class

### Expected behavior

Import `Actual`

### Installed versions

- actualpy version: 0.1.0
- Actual Server version: n/a

```bash
➜  ~ pip install actualpy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: actualpy in ./.local/lib/python3.12/site-packages (0.1.0)
```

**Comment by bvanelli** [comment]
Hello @wbradley93 , thanks for the report, I fixed and released a new version, you can now install version 0.1.1 from pip and it should work out of the box:

```bash
(venv) actualpy_test ➤ pip install actualpy                                                                                                 
...
(venv) actualpy_test ➤ source venv/bin/activate                                                                                             
(venv) actualpy_test ➤ python                                                                                                               
Python 3.11.8 (main, Mar 20 2024, 19:21:09) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from actual import Actual, __version__
>>> print(__version__)
0.1.1
```
