### ISSUE TITLE
run_rules() error

### ISSUE THREAD

**Issue by tcpr1** [bvanelli/actualpy#67]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of actualpy.

### Reproducible example

```python
with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
    actual.run_rules()
    actual.commit()
```

### Log output

```shell
Traceback (most recent call last):
  File "/config/actual-pluggy-py/actual-pluggy.py", line 27, in <module>
    actual.run_rules()
  File "/config/actual-pluggy-py/.conda/lib/python3.11/site-packages/actual/__init__.py", line 414, in run_rules
    ruleset = get_ruleset(self.session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/actual-pluggy-py/.conda/lib/python3.11/site-packages/actual/queries.py", line 604, in get_ruleset
    conditions = TypeAdapter(list[Condition]).validate_json(rule.conditions)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/actual-pluggy-py/.conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/actual-pluggy-py/.conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 393, in validate_json
    return self.validator.validate_json(data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for list[function-after[check_operation_type(), function-after[convert_value(), Condition]]]
0.type
  Input should be 'date', 'id', 'string', 'number' or 'boolean' [type=enum, input_value='imported_payee', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/enum
```

### Issue description

Example of rule set that broke the code: "imported payee **contains** XXXXXX -> set payee to YYYYYY"

### Expected behavior

do not get "exit code"

### Installed versions

- actualpy version: 0.4.0 - Actual Server version: 24.9.0

**Comment by bvanelli** [comment]
Closed as solved in https://github.com/bvanelli/actualpy/pull/70, the type of condition was not implemented, I might have skipped due to thinking it was a deprecated function.

You can try it locally and let me know if it works. I wrote some tests and also did some local testing too, and everything seems to work.
