### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by tcpr1** [bvanelli/actualpy#72]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of actualpy.

### Reproducible example

```python
from actual import Actual
with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
        current_date = datetime.now().strftime("%Y%m%d")
        actual.export_data(f"{FILE_ACTUAL}-{current_date}.zip")
        print("Data backed up.\n")
```

### Log output

```shell
ActualError: Actual found a table not supported by the library: table 'dashboard' not found

File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "/app/streamlit_app.py", line 70, in <module>
    backup_actual(URL_ACTUAL, PASSWORD_ACTUAL, FILE_ACTUAL)
File "/app/functions.py", line 10, in backup_actual
    with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
File "/usr/local/lib/python3.11/site-packages/actual/__init__.py", line 96, in __enter__
    self.download_budget(self._encryption_password)
File "/usr/local/lib/python3.11/site-packages/actual/__init__.py", line 337, in download_budget
    self.sync()
File "/usr/local/lib/python3.11/site-packages/actual/__init__.py", line 368, in sync
    self.apply_changes(changes.get_messages(self._master_key))
File "/usr/local/lib/python3.11/site-packages/actual/__init__.py", line 280, in apply_changes
    raise ActualError(
```

### Issue description

Code was working fine with a fresh budget file (used only for testing). But when I tried to run it with my real actual budget, it raised this error.. Maybe it has something to do with the new dashboard editing capabilities? 
Tried to replicate the error with mytesting budget file to pinpoint what is the cause, but could not replicate it yet.

### Expected behavior

Generate a backup file.

### Installed versions

- actualpy version: 0.4..0 - Actual Server version: 24.9..0

**Comment by bvanelli** [comment]
Hello, I really cannot reproduce your error, I have solved this issue on the latest version.

Can you ensure your environment has the correct library version?

```

from actual import Actual, __version__

print(version)
with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
        current_date = datetime.now().strftime("%Y%m%d")
        actual.export_data(f"{FILE_ACTUAL}-{current_date}.zip")
        print("Data backed up.\n")
```

**Comment by tcpr1** [comment]
I am trying to reproduce this error with another budget file, but could't yet...

Below a more complete output error when running my real budget (10 years long)

```
from actual import Actual, __version__
from datetime import datetime, timedelta

print(__version__)

with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
        current_date = datetime.now().strftime("%Y%m%d")
        actual.export_data(f"{FILE_ACTUAL}-{current_date}.zip")
        print("Data backed up.\n")`
```

0.4.0
[c:\git\actualpy\.conda\Lib\site-packages\actual\migrations.py:39](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/migrations.py:39): UserWarning: Migration query from migrations cannot be executed due to custom code, it will be skipped. Query:

UPDATE custom_reports SET conditions = ? WHERE id = ?

  warnings.warn(
[c:\git\actualpy\.conda\Lib\site-packages\actual\migrations.py:39](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/migrations.py:39): UserWarning: Migration query from migrations cannot be executed due to custom code, it will be skipped. Query:

INSERT INTO dashboard (id, type, width, height, x, y, meta) VALUES (?, ?, ?, ?, ?, ?, ?)

  warnings.warn(

---------------------------------------------------------------------------
ActualError                               Traceback (most recent call last)
Cell In[11], [line 16](vscode-notebook-cell:?execution_count=11&line=16)
     [15](vscode-notebook-cell:?execution_count=11&line=15) print(__version__)
---> [16](vscode-notebook-cell:?execution_count=11&line=16) with Actual(base_url=URL_ACTUAL, password=PASSWORD_ACTUAL, file=FILE_ACTUAL) as actual:
     [17](vscode-notebook-cell:?execution_count=11&line=17)         current_date = datetime.now().strftime("%Y%m%d")
     [18](vscode-notebook-cell:?execution_count=11&line=18)         actual.export_data(f"{FILE_ACTUAL}-{current_date}.zip")

File [c:\git\actualpy\.conda\Lib\site-packages\actual\__init__.py:96](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:96), in Actual.__enter__(self)
     [94](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:94) self._in_context = True
     [95](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:95) if self._file:
---> [96](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:96)     self.download_budget(self._encryption_password)
     [97](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:97) return self

File [c:\git\actualpy\.conda\Lib\site-packages\actual\__init__.py:337](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:337), in Actual.download_budget(self, encryption_password)
    [335](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:335) migration_files = self.data_file_index()
    [336](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:336) self.run_migrations(migration_files[1:])
--> [337](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:337) self.sync()
    [338](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:338) # create session if not existing
    [339](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:339) if self._in_context and not self._session:

File [c:\git\actualpy\.conda\Lib\site-packages\actual\__init__.py:368](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:368), in Actual.sync(self)
    [366](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:366) request.set_null_timestamp(client_id=self._client.client_id)  # using 0 timestamp to retrieve all changes
    [367](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:367) changes = self.sync_sync(request)
--> [368](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:368) self.apply_changes(changes.get_messages(self._master_key))
    [369](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:369) if changes.messages:
    [370](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:370)     self._client = HULC_Client.from_timestamp(changes.messages[-1].timestamp)

File [c:\git\actualpy\.conda\Lib\site-packages\actual\__init__.py:280](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:280), in Actual.apply_changes(self, messages)
    [278](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:278) table = get_class_from_reflected_table_name(self._meta, message.dataset)
    [279](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:279) if table is None:
--> [280](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:280)     raise ActualError(
    [281](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:281)         f"Actual found a table not supported by the library: table '{message.dataset}' not found\n"
    [282](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:282)     )
    [283](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:283) column = get_attribute_from_reflected_table_name(self._meta, message.dataset, message.column)
    [284](file:///C:/git/actualpy/.conda/Lib/site-packages/actual/__init__.py:284) if column is None:

ActualError: Actual found a table not supported by the library: table 'dashboard' not found

**Comment by tcpr1** [comment]
**Just solved the issue by reseting budget cache under Actual settings! 🙌**

**Comment by bvanelli** [comment]
Hello,

In general what happens with old files is:

- base file is pulled from server
- migrations are run on top of base file
- changlog is run on top of migrated database 

While writing this I realized that migrations need to be run *after* the migrations run, otherwise it doesn't make sense.

Thanks for the report, I'll fix this ASAP.
